version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/server"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "daily"