name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build-php:
    name: PHP
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [ '7.1' ]

    steps:
    - uses: actions/checkout@v3

    - name: Copy env file
      run: cp .env.dist .env

    - name: Setup PHP with tools
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        tools: composer

    - name: Composer self-update
      run: |
        cd server
        composer self-update --1

    - name: Validate composer.json and composer.lock
      run: |
        cd server
        composer validate --strict

    - name: Install dependencies
      run: |
        cd server
        composer install

    - name: Run test suite
      run: |
        cd server
        composer test
